# Generated by Django 2.2.3 on 2019-07-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_borrower_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrower_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Borrower ID'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='branch_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Branch ID'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
