# Generated by Django 2.2.3 on 2019-07-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CM_MTNMOBILEMONEY', 'CM_MTNMOBILEMONEY'), ('CM_ORANGEMONEY', 'CM_ORANGEMONEY')], max_length=50),
        ),
    ]
