# Generated by Django 2.2.3 on 2019-07-30 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190729_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ae22ff56-d655-4868-bd3a-6b855bf42aa0')),
        ),
    ]
