# Generated by Django 2.2.3 on 2019-07-30 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190730_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c3d92028-1961-4a5b-bd9b-0977de0c6d1e')),
        ),
    ]
