# Generated by Django 2.2.3 on 2019-07-30 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190730_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7a8cf446-af44-4630-8056-7698376cebb2')),
        ),
    ]
